from PyQt5.QtWidgets import QLineEdit,QLabel,QPushButton,QVBoxLayout,QHBoxLayout,QWidget,QComboBox
from Window_layouts.main_window_layout import title_font,basic_font,Icon,Qt

#Add lesson window
add_lesson_window = QWidget()
add_lesson_window.setWindowIcon(Icon)
add_lesson_window.resize(400,400)
add_lesson_window.setObjectName("main_window")
#Add lesson window layout
add_lesson_title = QLabel("Enter the day, hour and date to add the lesson")
add_lesson_title.setFont(title_font)
add_lesson_example = QLabel("Example:  Day: Monday  Hour: 14 50  Date: 30")
add_lesson_example.setFont(basic_font)
select_day_box = QComboBox()
select_day_box.setMinimumSize(120,20)
hour_line = QLineEdit()
hour_line.setPlaceholderText("Hour")
hour_line.setMaximumWidth(50)
minute_line = QLineEdit()
minute_line.setPlaceholderText("Minute")
minute_line.setMaximumWidth(50)
date_line = QLineEdit()
date_line.setPlaceholderText("Date")
add_lesson_button = QPushButton("Add")
add_lesson_button.setMinimumSize(180,20)
add_lesson_button.setMaximumSize(180,20)
add_lesson_button.setFont(basic_font)
data_layout = QHBoxLayout()
data_layout.addStretch(1)
data_layout.addWidget(select_day_box,alignment=Qt.AlignLeft | Qt.AlignVCenter)
data_layout.addStretch(2)
data_layout.addWidget(hour_line,alignment=Qt.AlignHCenter | Qt.AlignVCenter)
data_layout.addWidget(minute_line,alignment=Qt.AlignHCenter | Qt.AlignVCenter)
data_layout.addStretch(2)
data_layout.addWidget(date_line,alignment=Qt.AlignRight | Qt.AlignVCenter)
data_layout.addStretch(1)
Add_lesson_layout = QVBoxLayout()
Add_lesson_layout.addWidget(add_lesson_title,alignment=Qt.AlignHCenter)
Add_lesson_layout.addWidget(add_lesson_title,alignment=Qt.AlignHCenter)
Add_lesson_layout.addLayout(data_layout)
Add_lesson_layout.addWidget(add_lesson_button,alignment=Qt.AlignHCenter)

add_lesson_window.setLayout(Add_lesson_layout)