import os
from PyQt5.QtWidgets import QVBoxLayout,QHBoxLayout,QScrollArea,QPushButton,QLabel,QListWidget,QApplication,QWidget,QToolButton
from PyQt5.QtGui import QIcon,QFont
from PyQt5.QtCore import Qt,QSize

def find_file(file:str) -> str:
    "Return path to file"
    Path = os.path.join(os.environ.get("_MEIPASS2",os.path.abspath(".")),file).replace("\\","/")
    return Path if os.path.exists(Path) else print(f"[ERROR] File {Path} doesn't exist [ERROR]")

app = QApplication([])    
Icon = QIcon(find_file("Images/app icon.png"))
title_font = QFont("Arial",pointSize=20)
basic_font = QFont("Calibri",pointSize=10)#Calibri
list_font = QFont("Calibri",pointSize=15)

#Main window
main_window = QWidget()
main_window.setWindowIcon(Icon)
main_window.resize(1000,600)
main_window.setObjectName("main_window")
##Students list
students_list_title = QLabel("Students")
students_list_title.setFont(title_font)
students_list = QListWidget()
students_list.setFont(list_font)
students_list.setMinimumWidth(150)
add_student_button = QPushButton("Add a student")
add_student_button.setMinimumSize(110,20)
add_student_button.setFont(basic_font)
delete_student_button = QPushButton("Delete a student")
delete_student_button.setMinimumSize(110,20)
delete_student_button.setFont(basic_font)
rename_student_button = QPushButton("Rename a student")
rename_student_button.setMinimumSize(80,20)
rename_student_button.setFont(basic_font)

###Buttons layout
buttons_managment_list_layout = QHBoxLayout()
buttons_managment_list_layout.addWidget(add_student_button)
buttons_managment_list_layout.addWidget(delete_student_button)
Students_list_layout = QVBoxLayout()
Students_list_layout.addWidget(students_list_title,alignment=Qt.AlignHCenter)
Students_list_layout.addWidget(students_list)
Students_list_layout.addLayout(buttons_managment_list_layout)
Students_list_layout.addWidget(rename_student_button)
##Student's annual activity

###January
january_title = QLabel("January")
january_title.setFont(title_font)
january_day_title = QLabel("Day")
january_hour_title = QLabel("Hour")
january_date_title = QLabel("Date")
january_total_lessons_amount = QLabel("Total amount")
####January title layout
january_title_layout = QHBoxLayout()
january_title_layout.addWidget(january_day_title,alignment=Qt.AlignHCenter)
january_title_layout.addWidget(january_hour_title,alignment=Qt.AlignHCenter)
january_title_layout.addWidget(january_date_title,alignment=Qt.AlignHCenter)
january_title_layout.addWidget(january_total_lessons_amount,alignment=Qt.AlignHCenter)
january_activity_list = QListWidget()
january_activity_list.setFont(list_font)
january_activity_list.setMinimumWidth(350)
add_activity_to_january_button = QPushButton("Add a lesson to January")
add_activity_to_january_button.setMinimumSize(180,20)
add_activity_to_january_button.setMaximumSize(180,20)
add_activity_to_january_button.setFont(basic_font)
####January layout
January_layout = QVBoxLayout()
January_layout.addWidget(january_title,alignment=Qt.AlignHCenter)
January_layout.addLayout(january_title_layout)
January_layout.addWidget(january_activity_list,alignment=Qt.AlignHCenter)
January_layout.addWidget(add_activity_to_january_button,alignment=Qt.AlignHCenter)
####January window
January_window = QWidget()
January_window.setLayout(January_layout)

###February
february_title = QLabel("February")
february_title.setFont(title_font)
february_day_title = QLabel("Day")
february_hour_title = QLabel("Hour")
february_date_title = QLabel("Date")
february_total_lessons_amount = QLabel("Total amount")
####February title layout
february_title_layout = QHBoxLayout()
february_title_layout.addWidget(february_day_title,alignment=Qt.AlignHCenter)
february_title_layout.addWidget(february_hour_title,alignment=Qt.AlignHCenter)
february_title_layout.addWidget(february_date_title,alignment=Qt.AlignHCenter)
february_title_layout.addWidget(february_total_lessons_amount,alignment=Qt.AlignHCenter)
february_activity_list = QListWidget()
february_activity_list.setFont(list_font)
february_activity_list.setMinimumWidth(350)
add_activity_to_february_button = QPushButton("Add a lesson to February")
add_activity_to_february_button.setMinimumSize(180,20)
add_activity_to_february_button.setMaximumSize(180,20)
add_activity_to_february_button.setFont(basic_font)
####February layout
February_layout = QVBoxLayout()
February_layout.addWidget(february_title,alignment=Qt.AlignHCenter)
February_layout.addLayout(february_title_layout)
February_layout.addWidget(february_activity_list,alignment=Qt.AlignHCenter)
February_layout.addWidget(add_activity_to_february_button,alignment=Qt.AlignHCenter)
####February window
February_window = QWidget()
February_window.setLayout(February_layout)

###March
march_title = QLabel("March")
march_title.setFont(title_font)
march_day_title = QLabel("Day")
march_hour_title = QLabel("Hour")
march_date_title = QLabel("Date")
march_total_lessons_amount = QLabel("Total amount")
####March title layout
march_title_layout = QHBoxLayout()
march_title_layout.addWidget(march_day_title,alignment=Qt.AlignHCenter)
march_title_layout.addWidget(march_hour_title,alignment=Qt.AlignHCenter)
march_title_layout.addWidget(march_date_title,alignment=Qt.AlignHCenter)
march_title_layout.addWidget(march_total_lessons_amount,alignment=Qt.AlignHCenter)
march_activity_list = QListWidget()
march_activity_list.setFont(list_font)
march_activity_list.setMinimumWidth(350)
add_activity_to_march_button = QPushButton("Add a lesson to March")
add_activity_to_march_button.setMinimumSize(180,20)
add_activity_to_march_button.setMaximumSize(180,20)
add_activity_to_march_button.setFont(basic_font)
####March layout
March_layout = QVBoxLayout()
March_layout.addWidget(march_title,alignment=Qt.AlignHCenter)
March_layout.addLayout(march_title_layout)
March_layout.addWidget(march_activity_list,alignment=Qt.AlignHCenter)
March_layout.addWidget(add_activity_to_march_button,alignment=Qt.AlignHCenter)
####March window
March_window = QWidget()
March_window.setLayout(March_layout)

###April
april_title = QLabel("April")
april_title.setFont(title_font)
april_day_title = QLabel("Day")
april_hour_title = QLabel("Hour")
april_date_title = QLabel("Date")
april_total_lessons_amount = QLabel("Total amount")
####April title layout
april_title_layout = QHBoxLayout()
april_title_layout.addWidget(april_day_title,alignment=Qt.AlignHCenter)
april_title_layout.addWidget(april_hour_title,alignment=Qt.AlignHCenter)
april_title_layout.addWidget(april_date_title,alignment=Qt.AlignHCenter)
april_title_layout.addWidget(april_total_lessons_amount,alignment=Qt.AlignHCenter)
april_activity_list = QListWidget()
april_activity_list.setFont(list_font)
april_activity_list.setMinimumWidth(350)
add_activity_to_april_button = QPushButton("Add a lesson to April")
add_activity_to_april_button.setMinimumSize(180,20)
add_activity_to_april_button.setMaximumSize(180,20)
add_activity_to_april_button.setFont(basic_font)
####April layout
April_layout = QVBoxLayout()
April_layout.addWidget(april_title,alignment=Qt.AlignHCenter)
April_layout.addLayout(april_title_layout)
April_layout.addWidget(april_activity_list,alignment=Qt.AlignHCenter)
April_layout.addWidget(add_activity_to_april_button,alignment=Qt.AlignHCenter)
####April window
April_window = QWidget()
April_window.setLayout(April_layout)

###May
may_title = QLabel("May")
may_title.setFont(title_font)
may_day_title = QLabel("Day")
may_hour_title = QLabel("Hour")
may_date_title = QLabel("Date")
may_total_lessons_amount = QLabel("Total amount")
####May title layout
may_title_layout = QHBoxLayout()
may_title_layout.addWidget(may_day_title,alignment=Qt.AlignHCenter)
may_title_layout.addWidget(may_hour_title,alignment=Qt.AlignHCenter)
may_title_layout.addWidget(may_date_title,alignment=Qt.AlignHCenter)
may_title_layout.addWidget(may_total_lessons_amount,alignment=Qt.AlignHCenter)
may_activity_list = QListWidget()
may_activity_list.setFont(list_font)
may_activity_list.setMinimumWidth(350)
add_activity_to_may_button = QPushButton("Add a lesson to May")
add_activity_to_may_button.setMinimumSize(180,20)
add_activity_to_may_button.setMaximumSize(180,20)
add_activity_to_may_button.setFont(basic_font)
####May layout
May_layout = QVBoxLayout()
May_layout.addWidget(may_title,alignment=Qt.AlignHCenter)
May_layout.addLayout(may_title_layout)
May_layout.addWidget(may_activity_list,alignment=Qt.AlignHCenter)
May_layout.addWidget(add_activity_to_may_button,alignment=Qt.AlignHCenter)
####May window
May_window = QWidget()
May_window.setLayout(May_layout)

###June
june_title = QLabel("June")
june_title.setFont(title_font)
june_day_title = QLabel("Day")
june_hour_title = QLabel("Hour")
june_date_title = QLabel("Date")
june_total_lessons_amount = QLabel("Total amount")
####June title layout
june_title_layout = QHBoxLayout()
june_title_layout.addWidget(june_day_title,alignment=Qt.AlignHCenter)
june_title_layout.addWidget(june_hour_title,alignment=Qt.AlignHCenter)
june_title_layout.addWidget(june_date_title,alignment=Qt.AlignHCenter)
june_title_layout.addWidget(june_total_lessons_amount,alignment=Qt.AlignHCenter)
june_activity_list = QListWidget()
june_activity_list.setFont(list_font)
june_activity_list.setMinimumWidth(350)
add_activity_to_june_button = QPushButton("Add a lesson to June")
add_activity_to_june_button.setMinimumSize(180,20)
add_activity_to_june_button.setMaximumSize(180,20)
add_activity_to_june_button.setFont(basic_font)
####June layout
June_layout = QVBoxLayout()
June_layout.addWidget(june_title,alignment=Qt.AlignHCenter)
June_layout.addLayout(june_title_layout)
June_layout.addWidget(june_activity_list,alignment=Qt.AlignHCenter)
June_layout.addWidget(add_activity_to_june_button,alignment=Qt.AlignHCenter)
####June window
June_window = QWidget()
June_window.setLayout(June_layout)

###July
july_title = QLabel("July")
july_title.setFont(title_font)
july_day_title = QLabel("Day")
july_hour_title = QLabel("Hour")
july_date_title = QLabel("Date")
july_total_lessons_amount = QLabel("Total amount")
####July title layout
july_title_layout = QHBoxLayout()
july_title_layout.addWidget(july_day_title,alignment=Qt.AlignHCenter)
july_title_layout.addWidget(july_hour_title,alignment=Qt.AlignHCenter)
july_title_layout.addWidget(july_date_title,alignment=Qt.AlignHCenter)
july_title_layout.addWidget(july_total_lessons_amount,alignment=Qt.AlignHCenter)
july_activity_list = QListWidget()
july_activity_list.setFont(list_font)
july_activity_list.setMinimumWidth(350)
add_activity_to_july_button = QPushButton("Add a lesson to July")
add_activity_to_july_button.setMinimumSize(180,20)
add_activity_to_july_button.setMaximumSize(180,20)
add_activity_to_july_button.setFont(basic_font)
####July layout
July_layout = QVBoxLayout()
July_layout.addWidget(july_title,alignment=Qt.AlignHCenter)
July_layout.addLayout(july_title_layout)
July_layout.addWidget(july_activity_list,alignment=Qt.AlignHCenter)
July_layout.addWidget(add_activity_to_july_button,alignment=Qt.AlignHCenter)
####July window
July_window = QWidget()
July_window.setLayout(July_layout)

###August
august_title = QLabel("August")
august_title.setFont(title_font)
august_day_title = QLabel("Day")
august_hour_title = QLabel("Hour")
august_date_title = QLabel("Date")
august_total_lessons_amount = QLabel("Total amount")
####August title layout
august_title_layout = QHBoxLayout()
august_title_layout.addWidget(august_day_title,alignment=Qt.AlignHCenter)
august_title_layout.addWidget(august_hour_title,alignment=Qt.AlignHCenter)
august_title_layout.addWidget(august_date_title,alignment=Qt.AlignHCenter)
august_title_layout.addWidget(august_total_lessons_amount,alignment=Qt.AlignHCenter)
august_activity_list = QListWidget()
august_activity_list.setFont(list_font)
august_activity_list.setMinimumWidth(350)
add_activity_to_august_button = QPushButton("Add a lesson to August")
add_activity_to_august_button.setMinimumSize(180,20)
add_activity_to_august_button.setMaximumSize(180,20)
add_activity_to_august_button.setFont(basic_font)
####August layout
August_layout = QVBoxLayout()
August_layout.addWidget(august_title,alignment=Qt.AlignHCenter)
August_layout.addLayout(august_title_layout)
August_layout.addWidget(august_activity_list,alignment=Qt.AlignHCenter)
August_layout.addWidget(add_activity_to_august_button,alignment=Qt.AlignHCenter)
####August window
August_window = QWidget()
August_window.setLayout(August_layout)

###September
september_title = QLabel("September")
september_title.setFont(title_font)
september_day_title = QLabel("Day")
september_hour_title = QLabel("Hour")
september_date_title = QLabel("Date")
september_total_lessons_amount = QLabel("Total amount")
####September title layout
september_title_layout = QHBoxLayout()
september_title_layout.addWidget(september_day_title,alignment=Qt.AlignHCenter)
september_title_layout.addWidget(september_hour_title,alignment=Qt.AlignHCenter)
september_title_layout.addWidget(september_date_title,alignment=Qt.AlignHCenter)
september_title_layout.addWidget(september_total_lessons_amount,alignment=Qt.AlignHCenter)
september_activity_list = QListWidget()
september_activity_list.setFont(list_font)
september_activity_list.setMinimumWidth(350)
add_activity_to_september_button = QPushButton("Add a lesson to September")
add_activity_to_september_button.setMinimumSize(180,20)
add_activity_to_september_button.setMaximumSize(180,20)
add_activity_to_september_button.setFont(basic_font)
####September layout
September_layout = QVBoxLayout()
September_layout.addWidget(september_title,alignment=Qt.AlignHCenter)
September_layout.addLayout(september_title_layout)
September_layout.addWidget(september_activity_list,alignment=Qt.AlignHCenter)
September_layout.addWidget(add_activity_to_september_button,alignment=Qt.AlignHCenter)
####September window
September_window = QWidget()
September_window.setLayout(September_layout)

###October
october_title = QLabel("October")
october_title.setFont(title_font)
october_day_title = QLabel("Day")
october_hour_title = QLabel("Hour")
october_date_title = QLabel("Date")
october_total_lessons_amount = QLabel("Total amount")
####October title layout
october_title_layout = QHBoxLayout()
october_title_layout.addWidget(october_day_title,alignment=Qt.AlignHCenter)
october_title_layout.addWidget(october_hour_title,alignment=Qt.AlignHCenter)
october_title_layout.addWidget(october_date_title,alignment=Qt.AlignHCenter)
october_title_layout.addWidget(october_total_lessons_amount,alignment=Qt.AlignHCenter)
october_activity_list = QListWidget()
october_activity_list.setFont(list_font)
october_activity_list.setMinimumWidth(350)
add_activity_to_october_button = QPushButton("Add a lesson to October")
add_activity_to_october_button.setMinimumSize(180,20)
add_activity_to_october_button.setMaximumSize(180,20)
add_activity_to_october_button.setFont(basic_font)
####October layout
October_layout = QVBoxLayout()
October_layout.addWidget(october_title,alignment=Qt.AlignHCenter)
October_layout.addLayout(october_title_layout)
October_layout.addWidget(october_activity_list,alignment=Qt.AlignHCenter)
October_layout.addWidget(add_activity_to_october_button,alignment=Qt.AlignHCenter)
####October window
October_window = QWidget()
October_window.setLayout(October_layout)

###November
november_title = QLabel("November")
november_title.setFont(title_font)
november_day_title = QLabel("Day")
november_hour_title = QLabel("Hour")
november_date_title = QLabel("Date")
november_total_lessons_amount = QLabel("Total amount")
####November title layout
november_title_layout = QHBoxLayout()
november_title_layout.addWidget(november_day_title,alignment=Qt.AlignHCenter)
november_title_layout.addWidget(november_hour_title,alignment=Qt.AlignHCenter)
november_title_layout.addWidget(november_date_title,alignment=Qt.AlignHCenter)
november_title_layout.addWidget(november_total_lessons_amount,alignment=Qt.AlignHCenter)
november_activity_list = QListWidget()
november_activity_list.setFont(list_font)
november_activity_list.setMinimumWidth(350)
add_activity_to_november_button = QPushButton("Add a lesson to November")
add_activity_to_november_button.setMinimumSize(180,20)
add_activity_to_november_button.setMaximumSize(180,20)
add_activity_to_november_button.setFont(basic_font)
####November layout
November_layout = QVBoxLayout()
November_layout.addWidget(november_title,alignment=Qt.AlignHCenter)
November_layout.addLayout(november_title_layout)
November_layout.addWidget(november_activity_list,alignment=Qt.AlignHCenter)
November_layout.addWidget(add_activity_to_november_button,alignment=Qt.AlignHCenter)
####November window
November_window = QWidget()
November_window.setLayout(November_layout)

###December
december_title = QLabel("December")
december_title.setFont(title_font)
december_day_title = QLabel("Day")
december_hour_title = QLabel("Hour")
december_date_title = QLabel("Date")
december_total_lessons_amount = QLabel("Total amount")
####December title layout
december_title_layout = QHBoxLayout()
december_title_layout.addWidget(december_day_title,alignment=Qt.AlignHCenter)
december_title_layout.addWidget(december_hour_title,alignment=Qt.AlignHCenter)
december_title_layout.addWidget(december_date_title,alignment=Qt.AlignHCenter)
december_title_layout.addWidget(december_total_lessons_amount,alignment=Qt.AlignHCenter)
december_activity_list = QListWidget()
december_activity_list.setFont(list_font)
december_activity_list.setMinimumWidth(350)
add_activity_to_december_button = QPushButton("Add a lesson to December")
add_activity_to_december_button.setMinimumSize(180,20)
add_activity_to_december_button.setMaximumSize(180,20)
add_activity_to_december_button.setFont(basic_font)
####December layout
December_layout = QVBoxLayout()
December_layout.addWidget(december_title,alignment=Qt.AlignHCenter)
December_layout.addLayout(december_title_layout)
December_layout.addWidget(december_activity_list,alignment=Qt.AlignHCenter)
December_layout.addWidget(add_activity_to_december_button,alignment=Qt.AlignHCenter)
####December window
December_window = QWidget()
December_window.setLayout(December_layout)

###Scroll window layout
Scroll_window_layout = QHBoxLayout()
Scroll_window_layout.addWidget(January_window)
Scroll_window_layout.addWidget(February_window)
Scroll_window_layout.addWidget(March_window)
Scroll_window_layout.addWidget(April_window)
Scroll_window_layout.addWidget(May_window)
Scroll_window_layout.addWidget(June_window)
Scroll_window_layout.addWidget(July_window)
Scroll_window_layout.addWidget(August_window)
Scroll_window_layout.addWidget(September_window)
Scroll_window_layout.addWidget(October_window)
Scroll_window_layout.addWidget(November_window)
Scroll_window_layout.addWidget(December_window)
Scroll_window = QWidget()
Scroll_window.setLayout(Scroll_window_layout)
Scroll_window.setObjectName("Scroll_window")
Scroll_area = QScrollArea()
Scroll_area.setWidget(Scroll_window)
Scroll_area.setWidgetResizable(True)
Scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
Scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
####Year switch layout
previous_year_button = QPushButton("<")
previous_year_button.setMaximumSize(40,20)
previous_year_button.setMinimumSize(40,20)
next_year_button = QPushButton(">")
next_year_button.setMaximumSize(40,20)
next_year_button.setMinimumSize(40,20)
actual_year_title = QLabel("2022")
actual_year_title.setFont(title_font)
#####Switch languages button
Switch_languages_button = QPushButton("Switch language")
Switch_languages_button.setMinimumSize(180,20)
Switch_languages_button.setMaximumSize(180,20)
Switch_languages_button.setFont(basic_font)
Switch_themes_button = QToolButton()
Switch_themes_button.setIconSize(QSize(30,30))
year_switch_layout = QHBoxLayout()
year_switch_layout.addStretch(1)
year_switch_layout.addWidget(previous_year_button,alignment=Qt.AlignHCenter)
year_switch_layout.addWidget(actual_year_title,alignment=Qt.AlignHCenter)
year_switch_layout.addWidget(next_year_button,alignment=Qt.AlignHCenter)
year_switch_layout.addStretch(1)
year_switch_layout.addWidget(Switch_themes_button,alignment=Qt.AlignRight)
year_switch_layout.addWidget(Switch_languages_button,alignment=Qt.AlignRight)
total_lessons_amount_per_year = QLabel("Lessons:")
total_lessons_amount_per_year.setFont(title_font)
Scroll_layout = QVBoxLayout()
Scroll_layout.addLayout(year_switch_layout)
Scroll_layout.addWidget(total_lessons_amount_per_year,alignment=Qt.AlignHCenter)
Scroll_layout.addWidget(Scroll_area)
#Main_window_layout
Main_window_layout = QHBoxLayout()
Main_window_layout.addLayout(Students_list_layout,stretch=10)
Main_window_layout.addLayout(Scroll_layout,stretch=90)

main_window.setLayout(Main_window_layout)